server:
  port: 8080

#126邮箱SMTP服务器地址:smtp.126.com,端口号:465或者994
#163邮箱SMTP服务器地址:smtp.163.com,端口号:465或者994
#yeah邮箱SMTP服务器地址:smtp.yeah.net,端口号:465或者994
spring:
  mail:
    host: smtp.qq.com #发送邮件服务器 QQ邮箱配置
    port: 465 #端口号465或587
    username: 1321340821@qq.com #发送邮件的邮箱地址
    # 使用 jasypt 加密密码，使用com.fishleap.mail.PasswordTest.testGeneratePassword 生成加密密码，替换 ENC(加密密码)
    password:  xwnccckgqgovbabh #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    protocol: smtp
    test-connection: true
    #可以选择
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: springboot-mail
  freemarker:
    template-loader-path: classpath:/static/template/
    suffix: .ftl
    enabled: true
    cache: false
    allow-request-override: false
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

# 为 jasypt 配置解密秘钥
jasypt:
  encryptor:
    password: springboot-mail